### ISSUE TITLE
Add docker-based integration test infrastructure

### ISSUE THREAD

**Issue by heynickc** [AkkaNetContrib/Akka.Persistence.MySql#14]
To be consistent with SqlServer, Postgres, Cassandra plugins, test against a container running MySql

**Comment by heynickc** [comment]
@alexvaluyskiy this is an additional feature, not a bug fix.  this is how we test our other plugins against live databases to allow integration testing against different versions of the databases

**Comment by heynickc** [comment]
@alexvaluyskiy if you would like to discontinue testing our persistence plugins this way, please bring it up with the core team to reach a consensus and we will discontinue testing this way across all plugins

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy better off standardizing on Docker

**Comment by heynickc** [comment]
disregard, since this is a contrib package now
